# file: site.yml
#  ansible-playbook -v -i hosts-prereq site.yml --skip-tags "unsub" --vault-password-file ~/osev3/pw.txt 

#- hosts: ose-servers-all
- hosts: ose-servers-all-registry
  remote_user: root
  vars_files:
    - vars/vars.yml
    - vars/secrets.yml  
  roles:
    - vm-prereq-role